import os
from telegram import Update
from telegram.ext import (
    ApplicationBuilder,
    CommandHandler,
    MessageHandler,
    ContextTypes,
    filters,
)
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

# ===== CONFIG =====
TOKEN = os.getenv("BOT_TOKEN")  # Railway env variable

users = {}

# ===== START =====
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    uid = update.effective_user.id
    users[uid] = {"step": "name"}
    await update.message.reply_text(
        "⚜️ *𝐂𝐕 𝐁𝐘 𝐔𝐌𝐄𝐑*\n\n"
        "𝐋𝐞𝐭’𝐬 𝐜𝐫𝐞𝐚𝐭𝐞 𝐲𝐨𝐮𝐫 𝐩𝐫𝐨𝐟𝐞𝐬𝐬𝐢𝐨𝐧𝐚𝐥 𝐂𝐕.\n\n"
        "𝐒𝐞𝐧𝐝 𝐲𝐨𝐮𝐫 *𝐅𝐮𝐥𝐥 𝐍𝐚𝐦𝐞*:",
        parse_mode="Markdown"
    )

# ===== MESSAGE HANDLER =====
async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    uid = update.effective_user.id
    text = update.message.text.strip()

    if uid not in users:
        await start(update, context)
        return

    step = users[uid]["step"]

    if step == "name":
        users[uid]["name"] = text
        users[uid]["step"] = "phone"
        await update.message.reply_text("𝐒𝐞𝐧𝐝 𝐲𝐨𝐮𝐫 *𝐏𝐡𝐨𝐧𝐞 𝐍𝐮𝐦𝐛𝐞𝐫*:")

    elif step == "phone":
        users[uid]["phone"] = text
        users[uid]["step"] = "email"
        await update.message.reply_text("𝐒𝐞𝐧𝐝 𝐲𝐨𝐮𝐫 *𝐄𝐦𝐚𝐢𝐥 𝐀𝐝𝐝𝐫𝐞𝐬𝐬*:")

    elif step == "email":
        users[uid]["email"] = text
        users[uid]["step"] = "education"
        await update.message.reply_text("𝐒𝐞𝐧𝐝 𝐲𝐨𝐮𝐫 *𝐄𝐝𝐮𝐜𝐚𝐭𝐢𝐨𝐧*:")

    elif step == "education":
        users[uid]["education"] = text
        users[uid]["step"] = "experience"
        await update.message.reply_text("𝐒𝐞𝐧𝐝 𝐲𝐨𝐮𝐫 *𝐄𝐱𝐩𝐞𝐫𝐢𝐞𝐧𝐜𝐞*:")

    elif step == "experience":
        users[uid]["experience"] = text
        users[uid]["step"] = "skills"
        await update.message.reply_text(
            "𝐒𝐞𝐧𝐝 𝐲𝐨𝐮𝐫 *𝐒𝐤𝐢𝐥𝐥𝐬* (comma separated):"
        )

    elif step == "skills":
        users[uid]["skills"] = text
        users[uid]["step"] = "template"
        await update.message.reply_text(
            "𝐂𝐡𝐨𝐨𝐬𝐞 𝐂𝐕 𝐓𝐞𝐦𝐩𝐥𝐚𝐭𝐞:\n"
            "1️⃣ Modern\n"
            "2️⃣ Professional\n"
            "3️⃣ Minimal"
        )

    elif step == "template":
        if text not in ("1", "2", "3"):
            await update.message.reply_text("𝐏𝐥𝐞𝐚𝐬𝐞 𝐬𝐞𝐧𝐝 1, 2, 𝐨𝐫 3")
            return

        users[uid]["template"] = text
        pdf_path = generate_cv(uid)
        await update.message.reply_document(open(pdf_path, "rb"))
        await update.message.reply_text("✅ 𝐘𝐨𝐮𝐫 𝐂𝐕 𝐢𝐬 𝐑𝐞𝐚𝐝𝐲")
        users.pop(uid, None)

# ===== PDF GENERATOR =====
def generate_cv(uid: int) -> str:
    os.makedirs("resumes", exist_ok=True)
    path = f"resumes/cv_{uid}_{users[uid]['template']}.pdf"

    d = users[uid]
    template = d["template"]

    c = canvas.Canvas(path, pagesize=A4)
    width, height = A4
    y = height - 60

    # TEMPLATE STYLES
    if template == "1":  # Modern
        c.setFillColorRGB(0.1, 0.3, 0.6)
        c.rect(0, height - 90, width, 90, fill=1)
        c.setFillColorRGB(1, 1, 1)
        c.setFont("Helvetica-Bold", 22)
        c.drawString(50, height - 60, d["name"])
        c.setFillColorRGB(0, 0, 0)
        y = height - 130

    elif template == "2":  # Professional
        c.setFont("Helvetica-Bold", 24)
        c.drawCentredString(width / 2, y, d["name"])
        y -= 25
        c.line(50, y, width - 50, y)
        y -= 35

    else:  # Minimal
        c.setFont("Helvetica", 20)
        c.drawString(50, y, d["name"])
        y -= 30

    c.setFont("Helvetica", 11)
    c.drawString(50, y, f"{d['phone']} | {d['email']}")
    y -= 35

    def section(title, content):
        nonlocal y
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, y, title)
        y -= 16
        c.setFont("Helvetica", 11)
        for line in content.split("\n"):
            c.drawString(55, y, line)
            y -= 14
        y -= 10

    section("Education", d["education"])
    section("Experience", d["experience"])

    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "Skills")
    y -= 16
    c.setFont("Helvetica", 11)
    for s in d["skills"].split(","):
        c.drawString(55, y, f"- {s.strip()}")
        y -= 14

    c.setFont("Helvetica-Oblique", 9)
    c.drawCentredString(width / 2, 20, "Generated by CVbyUmer Bot")

    c.save()
    return path

# ===== MAIN =====
def main():
TOKEN = os.getenv("BOT_TOKEN") or "8520309436:AAFJbFy8cmz7ZLhcOhszVur7-qprL78UVx4"


    app = ApplicationBuilder().token(TOKEN).build()
    app.add_handler(CommandHandler("start", start))
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_message))
    app.run_polling()

if __name__ == "__main__":
    main()

